# Generated by Django 3.1.3 on 2021-07-03 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Last date time on which the object was modified.', verbose_name='modified_at')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ingredients/pictures')),
                ('description', models.TextField(blank=True)),
                ('is_veggie', models.BooleanField(help_text='Ingredients that do not contain meat or derivatives.')),
                ('is_vegan', models.BooleanField(help_text='Ingredients that do not come from animals.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-modified'),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
