# Generated by Django 3.1.3 on 2021-07-20 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0002_ingredient_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Last date time on which the object was modified.', verbose_name='modified_at')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug_name', models.SlugField(max_length=20, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='recipes/pictures')),
                ('description', models.CharField(blank=True, max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('is_veggie', models.BooleanField(default=False, help_text='Recipes with ingredients that do not contain meat or derivatives.')),
                ('is_vegan', models.BooleanField(default=False, help_text='Recipes with ingredients that do not come from animals.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='recipe_ingredients', to='ingredients.Ingredient')),
            ],
            options={
                'ordering': ('-created', '-modified'),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
